apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-cluster-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Vijayanand995/MongoTrail.git'
    targetRevision: HEAD
    path: mongo-trail-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true