apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Vijayanand995/MongoTrail.git'
    targetRevision: HEAD
    path: mongo-trail-chart
    helm:
      valueFiles:
        - values-staging.yaml   # Points directly to the nested staging overrides
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Vijayanand995/MongoTrail.git'
    targetRevision: HEAD
    path: mongo-trail-chart
    helm:
      valueFiles:
        - values-production.yaml # Points directly to the nested prod overrides
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true